
const BOOTSTRAP_APP = 'BOOTSTRAP_APP';

const INIT_NEW_GENERATION = 'INIT_NEW_GENERATION';
const HANDLE_NEXT_GENERATION = 'HANDLE_NEXT_GENERATION';

const HANDLE_RUN = 'HANDLE_RUN';
const HANDLE_STOP = 'HANDLE_STOP';

const allActionsTypes = {
  BOOTSTRAP_APP,

  INIT_NEW_GENERATION,
  HANDLE_NEXT_GENERATION,

  HANDLE_RUN,
  HANDLE_STOP
}

export default allActionsTypes;
